[project]
name = "blue-core-graph-explorer"
version = "1.4.0"
description = "Blue Core fork of LD4P Graph Explorer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "ruff>=0.14.1",
]
